add option to filter parameters
rum-and-code/airbrakex pull request #3
Opened 2023-03-28 19:54 UTC by decaruju

2023-03-28 20:09 UTC, GorillaCoffee approved these changes

2023-03-29 00:31 UTC, marcofiset requested changes
Good catch 👌🏻 et +1000 pour le test ✅ 

Quelques suggestions d'améliorations.

2023-03-29 00:31 UTC, marcofiset commented on lib/airbrakex/notifier.ex
> +        |> add(:params, filter_parameters(Keyword.get(options, :params), Config.get(:airbrakex, :filter_parameters, [])))
Cette ligne serait plus claire si on introduisait des variables intermédiaires. De plus, on peut passer un 3e argument à `Keyword.get` pour la valeur par défaut, et ainsi éviter le `(params || %{})` plus bas.

```suggestion
    config = Config.get(:airbrakex, :filter_parameters, [])
    params = Keyword.get(options, :params, %{}) # <--- valeur par défaut ici
    filtered_params = filter_parameters(params, config)
    
    # ...
    
        |> add(:params, filtered_params)
```

2023-03-29 00:31 UTC, marcofiset commented on lib/airbrakex/notifier.ex
> +  end
`Enum.into` supporte un callback comme 3e argument pour mapper sur les valeur du enum. Suite à la suggestion plus haut pour avoir une valeur par défaut pour params, on peut aussi retirer le `|| %{}` ici.

```suggestion
  defp filter_parameters(params, filtered_keys) do
    Enum.into(params, %{}, &filter_parameters(&1, filtered_keys))
  end
```

2023-03-29 00:31 UTC, marcofiset commented on lib/airbrakex/notifier.ex
> +    if Enum.member?(filtered_keys, Atom.to_string(key)), do: {key, "***"}, else: {key, value}
Privilégier simplement `to_string` ici au lieu de `Atom.to_string`. Ça fait la même chose pour les atoms, et ça ne plantera pas si quelqu'un décide de mettre une string comme key dans la config.
```suggestion
    if Enum.member?(filtered_keys, to_string(key)), do: {key, "***"}, else: {key, value}
```

2023-04-03 14:22 UTC, marcofiset approved these changes
Good job 👌🏻

2023-04-03 14:22 UTC, marcofiset commented on lib/airbrakex/notifier.ex
> +    for {key, value} <- params, into: %{} do
+1 pour `for into` 👏🏻  Je pense jamais d'utiliser ça, c'est pas mal nice!

2023-04-03 14:23 UTC, merged